language: generic

jobs:
  include:
    - language: java
      cache:
        directories:
          - .autoconf
          - $HOME/.m2
      script:
        - mvn clean install -q
    - language: node_js
      node_js: 12
      cache: npm
